config/routes.rb
Rails.application.routes.draw do
  
  root 'personas#index', as: 'personas_index'
  resources :personas

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/persona.rb
class Persona < ApplicationRecord
  validates :nombre, :presence => { :message => "Debe ingresar el nombre" }
  validates :apellido, :presence => { :message => "Debe ingresar el apellido" }
  validates :dni, format: { with: /\A\d+\z/, message: "Ingrese el número de documento." }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: %i[ show edit update destroy ]

  # GET /personas or /personas.json
  def index
   
    @personas = Persona.select("id, nombre, apellido, dni, fecha_de_nacimiento,
       strftime('%m', fecha_de_nacimiento) as mes, cast(strftime('%Y.%m%d', 'now') - strftime('%Y.%m%d', 
        fecha_de_nacimiento ) as int) as edad").order("mes")
    promedioEdades
  end

  def promedioEdades
    suma = 0
    @personas.each do |pers|
      suma = suma + pers.edad
    end
    @promedioEdades = (suma.to_f / @personas.all.size).round(2)
  end
  
  # GET /personas/1 or /personas/1.json
  def show
    age = Date.today.year - @persona.fecha_de_nacimiento.year
    
    if (Date.today.month < @persona.fecha_de_nacimiento.month)
      age -= 1
    end
    @edad = age
    
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas or /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: "La Persona ha sido creada correctamente." }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1 or /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: "La persona ha sido modificada con exito." }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1 or /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url, notice: "La Persona ha sido eliminada." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def persona_params
      params.require(:persona).permit(:nombre, :apellido, :fecha_de_nacimiento,:dni)
    end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%=javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
  <br>





    <%= yield %>
  </body>
</html>

app/views/personas/_form.html.erb
  <%= form_with(model: persona) do |form| %>
    <% if persona.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(persona.errors.count, "errores") %> Debe corregir los siguientes campos:</h2>

        <ul>
          <% persona.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="card">
      <div class="card-body">
        <div class="mb-3" >
          <%= form.label:nombre , {class:"form-label"} %>
          <%= form.text_field:nombre, {class: "form-coltrol", placeholder:"Ana "} %>
        </div>
        <div class="mb-3">
          <%= form.label:apellido, {class:"form-label"} %>
          <%= form.text_field:apellido, {class: "form-coltrol", placeholder:"Perez "}  %>
        </div>
        <div class="mb-3">
          <%= form.label:fecha_de_nacimiento, {class:"form-label"} %>
          <%= form.date_select:fecha_de_nacimiento, start_year: 1920, start_end: 2050%>
        </div>

        <div class="mb-3">
          <%= form.label:dni,  {class:"form-label"} %>
            
          <%= form.number_field:dni, type: "number", min:1 %>
        </div>

        
          <%= form.submit "Enviar", class: "btn btn-primary" %>
        
      </div>
    </div>

  <% end %>

app/views/personas/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>Editar Persona</h1>
      <%= render 'form', persona: @persona %>

      <%= link_to 'Detalle', @persona, :class => "btn btn-light" %> 
      <%= link_to 'Volver', personas_path, :class => "btn btn-light" %>
    </div>
  </div>
  
</div>

app/views/personas/index.html.erb
<p id="notice"><%= notice %></p>

<div>
  <%= link_to 'Nueva Persona', new_persona_path, :class => "btn btn-light" %> 
</div>


<div class="card">
  <div class="card-body">
    <h1>Personas</h1>

    <h3>Promedio de edad en años</h3>
    <%= @promedioEdades %>
  </div>
</div>

<div class="table-responsive">

  <table class="table">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">nombre</th>
        <th scope="col">apellido</th>
        <th scope="col">nacimiento</th>
        <th scope="col">dni</th>
        <th scope="col"> </th>
        <th scope="col"> </th>
        <th scope="col"> </th>

      </tr>
    </thead>

    <tbody>
    <% @personas.each do |persona| %>

      <tr>
        <th scope="row"><%= persona.id %></th>
        <td ><%= persona.nombre %></td>
        <td ><%= persona.apellido %></td>
        <td ><%= persona.fecha_de_nacimiento %></td>
        <td ><%= persona.dni %></td>
        <td><%= link_to 'Detalle', persona,  :class => "btn btn-light" %></td>
        <td><%= link_to 'Editar', edit_persona_path(persona), :class => "btn btn-light" %></td>
        <td><%= link_to 'Borrar', persona, method: :delete, data: { confirm: 'Estas seguro?' } , :class => "btn btn-light"%></td>
   
      </tr>

    <% end %>
    </tbody>
  </table>

</div>
<br>
<br>

app/views/personas/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>Crear Persona</h1>

      <%= render 'form', persona: @persona %>

      <%= link_to 'Volver', personas_path, :class => "btn btn-light"  %>
    </div>
  </div>
</div>

app/views/personas/show.html.erb
<div class="container">
   <div class="row">
    <div class="card col-12">
      <div class="card-body">
        <p id="notice"><%= notice %></p>

        <h2> Detalle de Persona</h2>

        <p>Nombre </p>
        <%= @persona.nombre %>
        <p>Apellido</p>
        <%= @persona.apellido %>
        <p>Fecha de nacimiento</p>
        <%= @persona.fecha_de_nacimiento %>
        <p>DNI</p>
        <%= @persona.dni %>
        <p>Edad en años</p>
        <%= @edad %>
        <br>
        <br>
        <%= link_to 'Editar', edit_persona_path(@persona), :class => "btn btn-light" %> |
        <%= link_to 'Volver', personas_path, :class => "btn btn-light" %>
      </div>
    </div>
  </div>
</div>